root = "." # The root directory of the project
tmp_dir = "tmp" # The temporary directory where air will store its temporary files

[build] # The build configuration
    cmd = "go build -o ./tmp/main ."# The command to build the project
    bin = "tmp/main" # The name of the binary file to be generated after building the project
    exclude_dir = ["tmp/*", "client/*"]  # Specifies the directories to be excluded from monitoring for changes
    include_file = ["**/*.go"] # Specifies the file patterns to be included for monitoring.
    ignore = ["tmp/*"] # Specifies the files or directories to be ignored when triggering a build.